name: Deploy Frontend to GitHub Pages

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  TAG: ${{ github.ref_name }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-frontend"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 直接部署静态文件到 GitHub Pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

