name: Deploy Frontend to GitHub Pages

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  TAG: ${{ github.ref_name }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-frontend"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        working-directory: ./frontend
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci
        # 或者使用 working-directory，但需要确保缓存生效

      - name: Build
        run: |
          cd frontend
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
